name: parma-mining-github
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Git
  - pre-commit
  # Python
  - pip
  - python =3.11
  - setuptools-scm
  - setuptools >=61 # pyproject.toml support
  # Development
  - types-pyyaml
  - python-dotenv>=1.0.0
  - pygithub>=2.1.1
  # Testing
  - pytest >=6 # --import-mode option
  - pytest-cov
  - httpx
  - pytest-mock
  # Dependencies (core)
  - fastapi >=0.104.0
  - polars >=0.19.0
  - pydantic >=2
  - pyyaml
  - uvicorn >=0.23.2
  - python-jose >=3.3.0
