name: CI
permissions: write-all
on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -el {0}

jobs:
  pre-commit-checks:
    name: Pre-commit Checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      PRE_COMMIT_USE_MICROMAMBA: 1
    steps:
      - uses: actions/checkout@v4
      - name: micromamba installation
        uses: mamba-org/setup-micromamba@9ef24caa388648dc149200514192b99bbf3563e4
      - name: add micromamba to GITHUB_PATH
        run: echo "${HOME}/micromamba-bin" >> "$GITHUB_PATH"
      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
        env:
          PRE_COMMIT_USE_MICROMAMBA: 1

  ci:
    name: Testing CI
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # TODO: include services database container once needed
    steps:
      - uses: actions/checkout@v4
      - name: conda env setup
        uses: mamba-org/setup-micromamba@9ef24caa388648dc149200514192b99bbf3563e4
        with:
          environment-file: environment.yml
          cache-environment: true
      - name: Install package
        run: python -m pip install --no-build-isolation --no-deps --disable-pip-version-check -e .
      - name: Run unit tests
        run: python -m pytest --cov-report=xml
      - name: Get Cover
        uses: orgoro/coverage@v3.1
        if: github.event_name == 'pull_request'
        with:
          coverageFile: ./coverage.xml
          token: ${{ github.token }}
  firebase-config:
    name: Firebase configurations
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Firebase Config
        uses: actions/checkout@v2
        env:
          FIREBASE_TYPE: ${{ secrets.FIREBASE_TYPE }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_CLIENT_ID: ${{ secrets.FIREBASE_CLIENT_ID }}
          FIREBASE_AUTH_URI: ${{ secrets.FIREBASE_AUTH_URI }}
          FIREBASE_TOKEN_URI: ${{ secrets.FIREBASE_TOKEN_URI }}
          FIREBASE_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.FIREBASE_AUTH_PROVIDER_X509_CERT_URL }}
          FIREBASE_CLIENT_X509_CERT_URL: ${{ secrets.FIREBASE_CLIENT_X509_CERT_URL }}
          FIREBASE_UNIVERSE_DOMAIN: ${{ secrets.FIREBASE_UNIVERSE_DOMAIN }}
